"""
PitchCoach — FastAPI backend for Vercel deployment.

Everything heavy runs remotely / as pure Python, so the function bundle stays
tiny (no torch, no xgboost, no numpy):
  - Audio transcription → Groq Whisper Large V3            (GROQ_API_KEY)
  - BERT embeddings     → HuggingFace feature-extraction   (HF_API_KEY + HF_MODEL_ID)
  - Classification      → pure-Python XGBoost evaluator     (api/model_predict.py)
  - Coaching feedback   → Google Gemini API                (GOOGLE_API_KEY)

The XGBoost model is shipped as a JSON tree dump (api/model_trees.json) and
evaluated in pure Python — so the good/bad prediction uses BERT embeddings +
linguistic features, and Gemini then explains that prediction.

Set the secrets in your Vercel project dashboard before deploying.
"""

import io
import os
import sys
from pathlib import Path

import httpx
import openai
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse

# Allow importing shared helpers from the project root when running on Vercel.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from gemini_utils import generate_gemini_text
from feature_utils import (
    EMBEDDING_DIM,
    clean_text,
    extract_text_features,
    features_to_vector,
    pool_hf_embedding,
    positive_prob,
)

# Pure-Python XGBoost evaluator (model_predict.py reads model_trees.json, both
# generated by train_xgboost.py). Bundling these instead of the xgboost library
# keeps the serverless function tiny — no xgboost / scipy / numpy at runtime.
sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    from model_predict import score as _xgb_score
except Exception:
    _xgb_score = None  # surfaced at request time with a clear error

# Frontend HTML is embedded as a Python module so import tracing bundles it
# reliably (data files in /api are not dependably bundled by Vercel).
from frontend import HTML as _INDEX_HTML

app = FastAPI(title="PitchCoach")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

ALLOWED_SUFFIXES = {".wav", ".mp3", ".m4a", ".ogg", ".flac", ".webm"}
MAX_AUDIO_BYTES = 25 * 1024 * 1024  # 25 MB (Groq free-tier audio file limit)


# ── helpers ───────────────────────────────────────────────────────────────────

def _require_env(name: str) -> str:
    val = os.environ.get(name, "")
    if not val:
        raise HTTPException(status_code=500, detail=f"Server missing env var: {name}")
    return val


async def _transcribe(audio_bytes: bytes, filename: str) -> str:
    # Groq hosts OpenAI's Whisper Large V3 behind an OpenAI-compatible API, so we
    # reuse the openai SDK pointed at Groq's base URL (no extra dependency).
    api_key = _require_env("GROQ_API_KEY")
    client = openai.OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")

    buf = io.BytesIO(audio_bytes)
    buf.name = filename  # SDK reads the .name attribute for MIME sniffing

    result = client.audio.transcriptions.create(model="whisper-large-v3", file=buf)
    return result.text.strip()


async def _embed(text: str) -> list:
    """
    Get a 768-d DistilBERT embedding via the HuggingFace feature-extraction
    pipeline, then mean-pool to a single vector (matches train_xgboost.py).

    If the model is still loading, HF returns HTTP 503; we retry once.
    """
    hf_token = _require_env("HF_API_KEY")
    model_id = _require_env("HF_MODEL_ID")
    url = f"https://api-inference.huggingface.co/pipeline/feature-extraction/{model_id}"
    headers = {"Authorization": f"Bearer {hf_token}"}
    payload = {"inputs": text, "options": {"wait_for_model": True}}

    async with httpx.AsyncClient(timeout=60) as client:
        resp = await client.post(url, headers=headers, json=payload)
        if resp.status_code == 503:
            resp = await client.post(url, headers=headers, json=payload)
        if resp.status_code != 200:
            raise HTTPException(
                status_code=502,
                detail=f"HuggingFace API error {resp.status_code}: {resp.text[:200]}",
            )
        data = resp.json()

    return pool_hf_embedding(data)


def _classify(embedding: list, features: dict) -> dict:
    """Score BERT embedding + linguistic features with the pure-Python evaluator."""
    if _xgb_score is None:
        raise HTTPException(
            status_code=500,
            detail="model_trees.json missing. Run train_xgboost.py and redeploy.",
        )

    ling = features_to_vector(features)
    vector = list(embedding) + list(ling)  # 776-length, pure Python list
    if len(vector) != EMBEDDING_DIM + len(ling):
        raise HTTPException(status_code=500, detail="Feature vector size mismatch.")

    good_prob = positive_prob(_xgb_score(vector))
    bad_prob = 1.0 - good_prob
    return {
        "model": "xgboost",
        "label": "good" if good_prob >= 0.5 else "bad",
        "good_prob": round(good_prob, 4),
        "bad_prob": round(bad_prob, 4),
    }


def _llm_feedback(transcript: str, classification: dict) -> str:
    api_key = os.environ.get("GOOGLE_API_KEY", "")
    if not api_key:
        return ""

    label = classification["label"]
    good_pct = int(classification["good_prob"] * 100)
    bad_pct = int(classification["bad_prob"] * 100)
    feat = classification.get("text_features", {})

    feature_block = f"""
Model output (XGBoost on BERT embeddings + linguistic features)
  • Verdict          : {label.upper()} ({good_pct}% good / {bad_pct}% bad)

Linguistic analysis
  • Words            : {feat.get("word_count", "?")}
  • Sentences        : {feat.get("sentence_count", "?")}  (avg {feat.get("avg_sentence_length", "?")} words/sentence)
  • Filler words     : {feat.get("filler_word_count", 0)} found — {", ".join(feat.get("filler_words_found", [])) or "none"}
  • Hedging phrases  : {", ".join(feat.get("hedge_phrases_found", [])) or "none"}
  • Data / numbers   : {", ".join(feat.get("data_points", [])) or "none mentioned"}
  • Questions asked  : {feat.get("question_count", 0)}"""

    prompt = f"""You are an expert pitch coach who has studied the world's most influential speeches.

A user recorded a business pitch. An XGBoost classifier (trained on DistilBERT embeddings +
engineered linguistic features from 83 labelled entrepreneur pitches) scored it below, along
with a linguistic analysis of the transcript. Use this evidence to ground every piece of
feedback you give.

{feature_block}

Transcript:
\"\"\"{transcript}\"\"\"

Give concise, actionable coaching feedback in 4 sections:

1. **Model verdict explained** — in 1-2 sentences, explain what the model's score reveals
   about why it classified this pitch as {label}.

2. **Strengths** — 2-3 bullet points on what worked well, referencing specific words or
   moments from the transcript where relevant.

3. **Areas to improve** — 2-3 bullet points on specific weaknesses with concrete fixes,
   calling out any filler words, hedging, missing data points, or structural gaps
   the analysis flagged.

4. **One key takeaway** — the single most impactful change the speaker should make.

Keep the tone encouraging but honest. Be specific to the evidence above."""

    return generate_gemini_text(api_key, prompt, max_output_tokens=2048)


# ── routes ────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def home():
    """Serve the single-page frontend directly from the function."""
    return _INDEX_HTML


@app.get("/api/health")
async def health():
    return {"status": "ok"}


@app.post("/api/analyze")
async def analyze(audio: UploadFile = File(...)):
    # --- validate file type ---
    import pathlib
    ext = pathlib.Path(audio.filename or "audio.wav").suffix.lower()
    if ext not in ALLOWED_SUFFIXES:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{ext}'. Use: {', '.join(ALLOWED_SUFFIXES)}",
        )

    audio_bytes = await audio.read()
    if len(audio_bytes) > MAX_AUDIO_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"File too large ({len(audio_bytes) // 1024 // 1024} MB). Max 25 MB.",
        )

    # --- transcribe ---
    try:
        transcript = await _transcribe(audio_bytes, audio.filename or f"audio{ext}")
    except openai.OpenAIError as e:
        raise HTTPException(status_code=502, detail=f"Whisper API error: {e}")

    if not transcript:
        raise HTTPException(status_code=422, detail="Whisper returned an empty transcript.")

    # --- embed (remote BERT) + linguistic features → XGBoost verdict ---
    features = extract_text_features(transcript)
    embedding = await _embed(clean_text(transcript))
    classification = _classify(embedding, features)
    classification["text_features"] = features

    # --- explain the verdict with Gemini ---
    feedback = _llm_feedback(transcript, classification)

    return {
        "transcript": transcript,
        "word_count": len(transcript.split()),
        "classification": classification,
        "feedback": feedback,
    }
