"""
Pure-Python evaluator for the PitchCoach XGBoost classifier.

Reads model_trees.json (generated by train_xgboost.py) and exposes `score()`.
No xgboost / scipy / numpy — keeps the Vercel serverless bundle tiny.

`score(features)` takes a 776-length list (768 BERT embedding + 8 linguistic
features) and returns P(good) in [0, 1].
"""

import json
import math
from pathlib import Path

_DATA = json.loads((Path(__file__).resolve().parent / "model_trees.json").read_text())
_BASE_MARGIN = _DATA["base_margin"]
_TREES = _DATA["trees"]


def _leaf_value(tree: dict, features) -> float:
    """Walk one tree from the root (node '0') to a leaf and return its value."""
    node = tree["0"]
    while "leaf" not in node:
        value = features[node["f"]]
        if value is None:
            nxt = node["missing"]
        elif value < node["thr"]:      # XGBoost: '<' goes to the 'yes' branch
            nxt = node["yes"]
        else:
            nxt = node["no"]
        node = tree[str(nxt)]
    return node["leaf"]


def score(features):
    """Return P(good) for a 776-length feature list."""
    margin = _BASE_MARGIN + sum(_leaf_value(t, features) for t in _TREES)
    return 1.0 / (1.0 + math.exp(-margin))
